apiVersion: v1
kind: Pod
metadata:
  name: go-http-server
  labels:
    app: go-http-server
spec:
  containers:
  - name: go-http-server
    image: go-http-server:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-http-server-service
  labels:
    app: go-http-server
spec:
  selector:
    app: go-http-server
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
