apiVersion: batch/v1
kind: Job
metadata:
  name: go-http-server-test-runner
spec:
  template:
    spec:
      containers:
      - name: test-runner
        image: golang:1.24-alpine
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Starting Go HTTP server tests..."
          cd /workspace
          go test -v ./test/...
        volumeMounts:
        - name: source-code
          mountPath: /workspace
        workingDir: /workspace
      restartPolicy: Never
      volumes:
      - name: source-code
        configMap:
          name: go-http-server-source
  backoffLimit: 1
